### PR TITLE
Grab updated version from ClearSkyInstitute.com

### PR DESCRIPTION
**Pull request by fang64**
I grabbed intermediates just to have them from archive.org but you can probably remove those from the PR. I was going to suggest a PKGBUILD change since you have it pointed to your github for updated versions.

### CODE REVIEW

**Comment by kj7rrv** [comment]
Thank you! Sorry it's been so long since I last updated this. I haven't been using Arch Linux lately, and I'd kind of forgotten about this. I can try to get my build system set back up (the partition it was on was corrupted), but I probably still won't be able to consistently release updates; would you be interested in taking over as maintainer of the AUR package?

**Comment by kj7rrv** [comment]
If you do want to take over as maintainer, here's the script I used to push updates:

```python
#!/usr/bin/env python3
import os
import sys
import hashlib
import requests

sizes = {
        '': '800x480',
        '-big': '1600x960',
        '-bigger': '2400x1440',
        '-huge': '3200x1920'
        }

version_lines = requests.get('https://clearskyinstitute.com/ham/HamClock/version.pl').text.split('\n')[:-1]
version = version_lines[0]

yn = input(f'Do you want to update the mirror to {version}? [Y/n] ')

if yn in 'Yy':
    changes = '\n'.join([f'* {i}' for i in version_lines[1:]])
    changes = f'[HamClock](https://clearskyinstitute.com/ham/HamClock/) version {version}\n\n{changes}\n'
    with open('changelog.md', 'w+') as f:
        f.write(changes)

    os.chdir('mirror')
    os.system(f'''rm -rf ESPHamClock ESPHamClock.tgz ESPHamClock.zip
    wget https://clearskyinstitute.com/ham/HamClock/ESPHamClock.tgz
    tar xzf ESPHamClock.tgz
    git add .
    git commit '-amv{version}'
    git push
    gh release create 'v{version}' -F ../changelog.md
    git fetch --tags origin
    git pull''')
    os.chdir('..')
else:
    yn = input('Do you want to release to the AUR? [Y/n] ')

if yn in 'Yy':
    url = f'https://github.com/kj7rrv/hamclock/archive/refs/tags/v{version}.tar.gz'
    sha256sum = hashlib.sha256(requests.get(url).content).hexdigest()

    rel = input('Enter release number: ')

    with open('PKGBUILD_template') as f:
        template = f.read()

    for suffix, size in sizes.items():
        with open(f'hamclock{suffix}/PKGBUILD', 'w+') as f:
            f.write(
                    template \
                            .replace('{{SUFFIX}}', suffix) \
                            .replace('{{REL}}', rel) \
                            .replace('{{VERSION}}', version) \
                            .replace('{{SIZE}}', size) \
                            .replace('{{PROVIDES}}', '' if (suffix == '') else '\'hamclock\'') \
                            .replace('{{HASH}}', sha256sum)
                    )

        os.system(f'cd hamclock{suffix} && makepkg --printsrcinfo > .SRCINFO')

    for suffix, size in sizes.items():
        os.system(f'cd hamclock{suffix} && git add -f PKGBUILD .SRCINFO && git commit -m "v{version}-{rel}" && git push')
```

**Comment by kj7rrv** [comment]
If you do want to take over as maintainer, here's the script I used to publish updates:

```python
#!/usr/bin/env python3
import os
import sys
import hashlib
import requests

sizes = {
        '': '800x480',
        '-big': '1600x960',
        '-bigger': '2400x1440',
        '-huge': '3200x1920'
        }

version_lines = requests.get('https://clearskyinstitute.com/ham/HamClock/version.pl').text.split('\n')[:-1]
version = version_lines[0]

yn = input(f'Do you want to update the mirror to {version}? [Y/n] ')

if yn in 'Yy':
    changes = '\n'.join([f'* {i}' for i in version_lines[1:]])
    changes = f'[HamClock](https://clearskyinstitute.com/ham/HamClock/) version {version}\n\n{changes}\n'
    with open('changelog.md', 'w+') as f:
        f.write(changes)

    os.chdir('mirror')
    os.system(f'''rm -rf ESPHamClock ESPHamClock.tgz ESPHamClock.zip
    wget https://clearskyinstitute.com/ham/HamClock/ESPHamClock.tgz
    tar xzf ESPHamClock.tgz
    git add .
    git commit '-amv{version}'
    git push
    gh release create 'v{version}' -F ../changelog.md
    git fetch --tags origin
    git pull''')
    os.chdir('..')
else:
    yn = input('Do you want to release to the AUR? [Y/n] ')

if yn in 'Yy':
    url = f'https://github.com/kj7rrv/hamclock/archive/refs/tags/v{version}.tar.gz'
    sha256sum = hashlib.sha256(requests.get(url).content).hexdigest()

    rel = input('Enter release number: ')

    with open('PKGBUILD_template') as f:
        template = f.read()

    for suffix, size in sizes.items():
        with open(f'hamclock{suffix}/PKGBUILD', 'w+') as f:
            f.write(
                    template \
                            .replace('{{SUFFIX}}', suffix) \
                            .replace('{{REL}}', rel) \
                            .replace('{{VERSION}}', version) \
                            .replace('{{SIZE}}', size) \
                            .replace('{{PROVIDES}}', '' if (suffix == '') else '\'hamclock\'') \
                            .replace('{{HASH}}', sha256sum)
                    )

        os.system(f'cd hamclock{suffix} && makepkg --printsrcinfo > .SRCINFO')

    for suffix, size in sizes.items():
        os.system(f'cd hamclock{suffix} && git add -f PKGBUILD .SRCINFO && git commit -m "v{version}-{rel}" && git push')
```

**Comment by fang64** [comment]
> Thank you! Sorry it's been so long since I last updated this. I haven't been using Arch Linux lately, and I'd kind of forgotten about this. I can try to get my build system set back up (the partition it was on was corrupted), but I probably still won't be able to consistently release updates; would you be interested in taking over as maintainer of the AUR package?

Yes I'll gladly take it over maintaining it on AUR. I actually was setting up a display then figured out it wasn't current :D So that's fine since I am running one locally.

If you want can you set me as co-maintainer for your hamclock AUR, if you want to disown then I think it'll make me maintainer at that point.

**Comment by kj7rrv** [comment]
@fang64 thank you! I added you as a maintainer on the AUR packages, and I gave you push access to this mirror. You should be able to use that script unmodified, but you will need the PKGBUILD template. The filesystem it was on got corrupted, but I have a program searching through the raw partition data now. I'll send you the `PKGBUILD_template` file once the program finds it.

**Comment by kj7rrv** [comment]
Here's the template:

```bash
# Maintainer: Samuel Sloniker <sam@kj7rrv.com>

pkgname=hamclock{{SUFFIX}}
pkgver={{VERSION}}
pkgrel={{REL}}
epoch=
pkgdesc="Clock and world map with extra features for amateur radio ({{SIZE}} version)"
arch=('x86_64' 'aarch64')
url="https://clearskyinstitute.com/ham/HamClock"
license=('MIT')
groups=()
depends=('libx11' 'libxcb')
makedepends=()
checkdepends=()
optdepends=()
provides=({{PROVIDES}})
conflicts=({{PROVIDES}})
replaces=()
backup=()
options=()
install=
changelog=
source=("https://github.com/kj7rrv/hamclock/archive/refs/tags/v$pkgver.tar.gz")
noextract=()
sha256sums=('{{HASH}}')
validpgpkeys=()

prepare() {
	cd "hamclock-$pkgver/ESPHamClock"
	# Add -AUR to version
	sed -i 's/"/-AUR"/g' version.h
	sed -i 's/\t-AUR"/\t"/g' version.h

	# Do not check for/install updates
	sed -i "s/tft.print (F(\"You're up to date\!\"));"'/tft.print(F("Updates disabled for AUR")); tft.setCursor (tft.width()\/8, tft.height()\/3+40); tft.print(F("If this build is outdated by more than a few days,")); tft.setCursor (tft.width()\/8, tft.height()\/3+80); tft.print(F("please email sam@kj7rrv.com.")); wdDelay(2000);/g' ESPHamClock.ino
	sed -i 's/bool found_newer = false;/return false;bool found_newer;/g' OTAupdate.cpp
}

build() {
	cd "hamclock-$pkgver/ESPHamClock"
	make -j 4 hamclock-{{SIZE}}
}

package() {
	cd "hamclock-$pkgver/ESPHamClock"
	mkdir -p "$pkgdir/usr/bin" "$pkgdir/usr/share/applications" "$pkgdir/usr/share/icons" "$pkgdir/usr/share/licenses/$pkgname/"
	cp hamclock-{{SIZE}} "$pkgdir/usr/bin/hamclock"
	cp hamclock.png "$pkgdir/usr/share/icons"
	cp LICENSE "$pkgdir/usr/share/licenses/$pkgname"
	cat > "$pkgdir/usr/share/applications/hamclock.desktop" << HERE
[Desktop Entry]
Name=HamClock
Exec=hamclock
Icon=/usr/share/icons/hamclock.png
Terminal=false
Type=Application
Categories=HamRadio
HERE
}
```

You'll need to create a directory to store all of the data; in that directory, you'll need the script (any `.py` file name of your choice is fine), the template saved as `PKGBUILD_template`, this repository cloned as `mirror`, and each of the AUR package repos (`hamclock`, `hamclock-big`, `hamclock-bigger`, and `hamclock-huge`) cloned under their own names. To run the script, you'll need Python, the `requests` package from PyPI, and `git`, `gh`, and the software needed to build HamClock.

**Pull request merged**
